services:
    contacts-app:
        build: 
            context: .
            dockerfile: Dockerfile
       
        environment: 
            ASPNETCORE_ENVIRONMENT: Development
        ports: 
            - "32768:8080"

    postgresql: 
        image: postgres
        command: -c listen_addresses='*'
        volumes:
            - postgredata:/data/db
        ports:
            - "5432:5432"
        environment:
        # Should be read from env variables in prod
            POSTGRES_PASSWORD: testThreeTwoOne
        healthcheck:
            test: ["CMD-SHELL","pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
volumes:
    postgredata:
        
  